use_default_settings: true
default_doi_resolver: oadoi.org

server:
  limiter: false

search:
  formats:
    - html
    - json
  suspended_times:
    SearxEngineCaptcha: 0
    SearxEngineTooManyRequests: 0
    SearxEngineAccessDenied: 0

outgoing:
  request_timeout: 10.0
  max_request_timeout: 25.0
  pool_connections: 100
  pool_maxsize: 20
  extra_proxy_timeout: 10
  retries: 2
